// All IANA timezones grouped for the select dropdown.
// Each entry has: value (IANA zone), label (bilingual display), tad (timeanddate.com worldclock path).
const TIMEZONE_LIST = [
  { value: 'Pacific/Midway',      label: '(UTC-11:00) Midway / 中途岛',                          tad: 'pacific/apia' },
  { value: 'Pacific/Honolulu',    label: '(UTC-10:00) Honolulu / 夏威夷-檀香山',                  tad: 'usa/honolulu' },
  { value: 'America/Anchorage',   label: '(UTC-09:00) Anchorage / 安克雷奇',                      tad: 'usa/anchorage' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Los Angeles / 洛杉矶',                      tad: 'usa/los-angeles' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) San Francisco / 旧金山',                    tad: 'usa/san-francisco' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) San Diego / 圣地亚哥',                        tad: 'usa/san-diego' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Seattle / 西雅图',                            tad: 'usa/seattle' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Portland / 波特兰',                          tad: 'usa/portland' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Las Vegas / 拉斯维加斯',                      tad: 'usa/las-vegas' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) San Jose / 圣何塞',                         tad: 'usa/san-jose' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Sacramento / 萨克拉门托',                   tad: 'usa/sacramento' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Oakland / 奥克兰',                         tad: 'usa/oakland' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Anaheim / 阿纳海姆',                         tad: 'usa/anaheim' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Irvine / 欧文',                              tad: 'usa/irvine' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Long Beach / 长滩',                         tad: 'usa/long-beach' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Santa Ana / 圣安娜',                         tad: 'usa/santa-ana' },
  { value: 'America/Vancouver',   label: '(UTC-08:00) Vancouver / 温哥华',                        tad: 'canada/vancouver' },
  { value: 'America/Denver',      label: '(UTC-07:00) Denver / 丹佛',                             tad: 'usa/denver' },
  { value: 'America/Denver',      label: '(UTC-07:00) Salt Lake City / 盐湖城',                     tad: 'usa/salt-lake-city' },
  { value: 'America/Denver',      label: '(UTC-07:00) Albuquerque / 阿尔伯克基',                   tad: 'usa/albuquerque' },
  { value: 'America/Boise',       label: '(UTC-07:00) Boise / 博伊西',                             tad: 'usa/boise' },
  { value: 'America/Denver',      label: '(UTC-07:00) Colorado Springs / 科罗拉多斯普林斯',          tad: 'usa/colorado-springs' },
  { value: 'America/Denver',      label: '(UTC-07:00) Fort Collins / 柯林斯堡',                     tad: 'usa/fort-collins' },
  { value: 'America/Denver',      label: '(UTC-07:00) Cheyenne / 夏延',                            tad: 'usa/cheyenne' },
  { value: 'America/Denver',      label: '(UTC-07:00) Grand Junction / 大章克申',                   tad: 'usa/grand-junction' },
  { value: 'America/Phoenix',     label: '(UTC-07:00) Phoenix / 菲尼克斯',                        tad: 'usa/phoenix' },
  { value: 'America/Phoenix',     label: '(UTC-07:00) Tucson / 图森',                              tad: 'usa/tucson' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Chicago / 芝加哥',                          tad: 'usa/chicago' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Houston / 休斯顿',                          tad: 'usa/houston' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Dallas / 达拉斯',                            tad: 'usa/dallas' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Minneapolis / 明尼阿波利斯',                  tad: 'usa/minneapolis' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Kansas City / 堪萨斯城',                     tad: 'usa/kansas-city' },
  { value: 'America/Chicago',     label: '(UTC-06:00) New Orleans / 新奥尔良',                      tad: 'usa/new-orleans' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Nashville / 纳什维尔',                        tad: 'usa/nashville' },
  { value: 'America/Chicago',     label: '(UTC-06:00) St. Louis / 圣路易斯',                        tad: 'usa/st-louis' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Milwaukee / 密尔沃基',                        tad: 'usa/milwaukee' },
  { value: 'America/Chicago',     label: '(UTC-06:00) St. Paul / 圣保罗',                          tad: 'usa/st-paul' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Omaha / 奥马哈',                              tad: 'usa/omaha' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Wichita / 威奇托',                            tad: 'usa/wichita' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Tulsa / 塔尔萨',                              tad: 'usa/tulsa' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Oklahoma City / 俄克拉荷马城',              tad: 'usa/oklahoma-city' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Des Moines / 得梅因',                         tad: 'usa/des-moines' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Memphis / 孟菲斯',                            tad: 'usa/memphis' },
  { value: 'America/Mexico_City', label: '(UTC-06:00) Mexico City / 墨西哥城',                    tad: 'mexico/mexico-city' },
  { value: 'America/Toronto',     label: '(UTC-05:00) Toronto / 多伦多',                          tad: 'canada/toronto' },
  { value: 'America/New_York',    label: '(UTC-05:00) New York / 纽约',                           tad: 'usa/new-york' },
  { value: 'America/New_York',    label: '(UTC-05:00) Boston / 波士顿',                            tad: 'usa/boston' },
  { value: 'America/New_York',    label: '(UTC-05:00) Philadelphia / 费城',                        tad: 'usa/philadelphia' },
  { value: 'America/New_York',    label: '(UTC-05:00) Washington / 华盛顿',                        tad: 'usa/washington' },
  { value: 'America/New_York',    label: '(UTC-05:00) Atlanta / 亚特兰大',                         tad: 'usa/atlanta' },
  { value: 'America/New_York',    label: '(UTC-05:00) Miami / 迈阿密',                              tad: 'usa/miami' },
  { value: 'America/New_York',    label: '(UTC-05:00) Charlotte / 夏洛特',                         tad: 'usa/charlotte' },
  { value: 'America/New_York',    label: '(UTC-05:00) Baltimore / 巴尔的摩',                        tad: 'usa/baltimore' },
  { value: 'America/New_York',    label: '(UTC-05:00) Columbus / 哥伦布',                          tad: 'usa/columbus' },
  { value: 'America/New_York',    label: '(UTC-05:00) Cincinnati / 辛辛那提',                      tad: 'usa/cincinnati' },
  { value: 'America/New_York',    label: '(UTC-05:00) Pittsburgh / 匹兹堡',                        tad: 'usa/pittsburgh' },
  { value: 'America/New_York',    label: '(UTC-05:00) Buffalo / 布法罗',                            tad: 'usa/buffalo' },
  { value: 'America/New_York',    label: '(UTC-05:00) Rochester / 罗切斯特',                        tad: 'usa/rochester' },
  { value: 'America/New_York',    label: '(UTC-05:00) Albany / 奥尔巴尼',                          tad: 'usa/albany' },
  { value: 'America/New_York',    label: '(UTC-05:00) Providence / 普罗维登斯',                    tad: 'usa/providence' },
  { value: 'America/New_York',    label: '(UTC-05:00) Hartford / 哈特福德',                        tad: 'usa/hartford' },
  { value: 'America/New_York',    label: '(UTC-05:00) Tampa / 坦帕',                                tad: 'usa/tampa' },
  { value: 'America/New_York',    label: '(UTC-05:00) Orlando / 奥兰多',                           tad: 'usa/orlando' },
  { value: 'America/New_York',    label: '(UTC-05:00) Jacksonville / 杰克逊维尔',                  tad: 'usa/jacksonville' },
  { value: 'America/New_York',    label: '(UTC-05:00) Richmond / 里士满',                          tad: 'usa/richmond' },
  { value: 'America/New_York',    label: '(UTC-05:00) Norfolk / 诺福克',                            tad: 'usa/norfolk' },
  { value: 'America/New_York',    label: '(UTC-05:00) Charleston / 查尔斯顿',                      tad: 'usa/charleston' },
  { value: 'America/New_York',    label: '(UTC-05:00) Savannah / 萨凡纳',                          tad: 'usa/savannah' },
  { value: 'America/Bogota',      label: '(UTC-05:00) Bogotá / 波哥大',                           tad: 'colombia/bogota' },
  { value: 'America/Lima',        label: '(UTC-05:00) Lima / 利马',                               tad: 'peru/lima' },
  { value: 'America/Guayaquil',   label: '(UTC-05:00) Quito / 基多',                              tad: 'ecuador/quito' },
  { value: 'America/Detroit',     label: '(UTC-05:00) Detroit / 底特律',                          tad: 'usa/detroit' },
  { value: 'America/Indiana/Indianapolis', label: '(UTC-05:00) Indianapolis / 印第安纳波利斯',    tad: 'usa/indianapolis' },
  { value: 'America/Halifax',     label: '(UTC-04:00) Halifax / 哈利法克斯',                      tad: 'canada/halifax' },
  { value: 'America/Caracas',     label: '(UTC-04:30) Caracas / 加拉加斯',                        tad: 'venezuela/caracas' },
  { value: 'America/Santiago',    label: '(UTC-04:00) Santiago / 圣地亚哥',                       tad: 'chile/santiago' },
  { value: 'America/La_Paz',      label: '(UTC-04:00) La Paz / 拉巴斯',                          tad: 'bolivia/la-paz' },
  { value: 'America/Asuncion',    label: '(UTC-04:00) Asunción / 亚松森',                         tad: 'paraguay/asuncion' },
  { value: 'America/Sao_Paulo',   label: '(UTC-03:00) São Paulo / 圣保罗',                        tad: 'brazil/sao-paulo' },
  { value: 'America/Sao_Paulo',   label: '(UTC-03:00) Rio de Janeiro / 里约热内卢',                 tad: 'brazil/rio-de-janeiro' },
  { value: 'America/Sao_Paulo',   label: '(UTC-03:00) Brasília / 巴西利亚',                         tad: 'brazil/brasilia' },
  { value: 'America/Sao_Paulo',   label: '(UTC-03:00) Salvador / 萨尔瓦多',                        tad: 'brazil/salvador' },
  { value: 'America/Argentina/Buenos_Aires', label: '(UTC-03:00) Córdoba / 科尔多瓦',                  tad: 'argentina/cordoba' },
  { value: 'America/Argentina/Buenos_Aires', label: '(UTC-03:00) Buenos Aires / 布宜诺斯艾利斯',  tad: 'argentina/buenos-aires' },
  { value: 'America/Montevideo',  label: '(UTC-03:00) Montevideo / 蒙得维的亚',                   tad: 'uruguay/montevideo' },

  { value: 'Europe/London',       label: '(UTC+00:00) London / 伦敦',                             tad: 'uk/london' },
  { value: 'Europe/London',       label: '(UTC+00:00) Manchester / 曼彻斯特',                     tad: 'uk/manchester' },
  { value: 'Europe/London',       label: '(UTC+00:00) Edinburgh / 爱丁堡',                       tad: 'uk/edinburgh' },
  { value: 'Europe/Dublin',       label: '(UTC+00:00) Dublin / 都柏林',                           tad: 'ireland/dublin' },
  { value: 'Europe/Dublin',       label: '(UTC+00:00) Cork / 科克',                               tad: 'ireland/cork' },
  { value: 'Europe/Lisbon',       label: '(UTC+00:00) Lisbon / 里斯本',                           tad: 'portugal/lisbon' },
  { value: 'Europe/Lisbon',       label: '(UTC+00:00) Porto / 波尔图',                            tad: 'portugal/porto' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Paris / 巴黎',                              tad: 'france/paris' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Marseille / 马赛',                           tad: 'france/marseille' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Lyon / 里昂',                                tad: 'france/lyon' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Nice / 尼斯',                               tad: 'france/nice' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Toulouse / 图卢兹',                         tad: 'france/toulouse' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Lille / 里尔',                               tad: 'france/lille' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Strasbourg / 斯特拉斯堡',                   tad: 'france/strasbourg' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Nantes / 南特',                              tad: 'france/nantes' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Bordeaux / 波尔多',                          tad: 'france/bordeaux' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Montpellier / 蒙彼利埃',                     tad: 'france/montpellier' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Berlin / 柏林',                             tad: 'germany/berlin' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Hamburg / 汉堡',                             tad: 'germany/hamburg' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Munich / 慕尼黑',                             tad: 'germany/munich' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Düsseldorf / 杜塞尔多夫',                    tad: 'germany/dusseldorf' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Frankfurt / 法兰克福',                        tad: 'germany/frankfurt' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Cologne / 科隆',                             tad: 'germany/cologne' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Stuttgart / 斯图加特',                       tad: 'germany/stuttgart' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Leipzig / 莱比锡',                            tad: 'germany/leipzig' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Dresden / 德累斯顿',                          tad: 'germany/dresden' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Hannover / 汉诺威',                          tad: 'germany/hannover' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Bremen / 不来梅',                             tad: 'germany/bremen' },
  { value: 'Europe/Amsterdam',    label: '(UTC+01:00) Amsterdam / 阿姆斯特丹',                    tad: 'netherlands/amsterdam' },
  { value: 'Europe/Amsterdam',    label: '(UTC+01:00) Rotterdam / 鹿特丹',                        tad: 'netherlands/rotterdam' },
  { value: 'Europe/Amsterdam',    label: '(UTC+01:00) The Hague / 海牙',                              tad: 'netherlands/the-hague' },
  { value: 'Europe/Amsterdam',    label: '(UTC+01:00) Utrecht / 乌得勒支',                          tad: 'netherlands/utrecht' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Zurich / 苏黎世',                           tad: 'switzerland/zurich' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Geneva / 日内瓦',                            tad: 'switzerland/geneva' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Basel / 巴塞尔',                              tad: 'switzerland/basel' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Bern / 伯尔尼',                               tad: 'switzerland/bern' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Lausanne / 洛桑',                             tad: 'switzerland/lausanne' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Lucerne / 卢塞恩',                            tad: 'switzerland/lucerne' },
  { value: 'Europe/Madrid',       label: '(UTC+01:00) Madrid / 马德里',                           tad: 'spain/madrid' },
  { value: 'Europe/Madrid',       label: '(UTC+01:00) Barcelona / 巴塞罗那',                       tad: 'spain/barcelona' },
  { value: 'Europe/Madrid',       label: '(UTC+01:00) Valencia / 瓦伦西亚',                         tad: 'spain/valencia' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Rome / 罗马',                               tad: 'italy/rome' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Milan / 米兰',                               tad: 'italy/milan' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Venice / 威尼斯',                            tad: 'italy/venice' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Naples / 那不勒斯',                          tad: 'italy/naples' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Florence / 佛罗伦萨',                         tad: 'italy/florence' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Turin / 都灵',                                tad: 'italy/turin' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Palermo / 巴勒莫',                           tad: 'italy/palermo' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Genoa / 热那亚',                             tad: 'italy/genoa' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Bologna / 博洛尼亚',                          tad: 'italy/bologna' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Bari / 巴里',                                tad: 'italy/bari' },
  { value: 'Europe/Stockholm',    label: '(UTC+01:00) Stockholm / 斯德哥尔摩',                    tad: 'sweden/stockholm' },
  { value: 'Europe/Oslo',         label: '(UTC+01:00) Oslo / 奥斯陆',                             tad: 'norway/oslo' },
  { value: 'Europe/Copenhagen',   label: '(UTC+01:00) Copenhagen / 哥本哈根',                     tad: 'denmark/copenhagen' },
  { value: 'Europe/Prague',       label: '(UTC+01:00) Prague / 布拉格',                           tad: 'czech-republic/prague' },
  { value: 'Europe/Prague',       label: '(UTC+01:00) Brno / 布尔诺',                              tad: 'czech-republic/brno' },
  { value: 'Europe/Prague',       label: '(UTC+01:00) Ostrava / 奥斯特拉发',                        tad: 'czech-republic/ostrava' },
  { value: 'Europe/Brussels',     label: '(UTC+01:00) Brussels / 布鲁塞尔',                       tad: 'belgium/brussels' },
  { value: 'Europe/Brussels',     label: '(UTC+01:00) Antwerp / 安特卫普',                         tad: 'belgium/antwerp' },
  { value: 'Europe/Brussels',     label: '(UTC+01:00) Ghent / 根特',                               tad: 'belgium/ghent' },
  { value: 'Europe/Brussels',     label: '(UTC+01:00) Bruges / 布鲁日',                             tad: 'belgium/bruges' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Vienna / 维也纳',                           tad: 'austria/vienna' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Graz / 格拉茨',                               tad: 'austria/graz' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Innsbruck / 因斯布鲁克',                     tad: 'austria/innsbruck' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Salzburg / 萨尔茨堡',                        tad: 'austria/salzburg' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Linz / 林茨',                                tad: 'austria/linz' },
  { value: 'Europe/Budapest',     label: '(UTC+01:00) Budapest / 布达佩斯',                       tad: 'hungary/budapest' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Warsaw / 华沙',                             tad: 'poland/warsaw' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Krakow / 克拉科夫',                           tad: 'poland/krakow' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Gdansk / 格但斯克',                           tad: 'poland/gdansk' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Wroclaw / 弗罗茨瓦夫',                         tad: 'poland/wroclaw' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Poznan / 波兹南',                             tad: 'poland/poznan' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Lublin / 卢布林',                             tad: 'poland/lublin' },
  { value: 'Europe/Zagreb',       label: '(UTC+01:00) Zagreb / 萨格勒布',                         tad: 'croatia/zagreb' },
  { value: 'Europe/Belgrade',     label: '(UTC+01:00) Belgrade / 贝尔格莱德',                     tad: 'serbia/belgrade' },
  { value: 'Europe/Bratislava',   label: '(UTC+01:00) Bratislava / 布拉迪斯拉发',                 tad: 'slovakia/bratislava' },
  { value: 'Europe/Ljubljana',    label: '(UTC+01:00) Ljubljana / 卢布尔雅那',                    tad: 'slovenia/ljubljana' },
  { value: 'Europe/Athens',       label: '(UTC+02:00) Athens / 雅典',                             tad: 'greece/athens' },
  { value: 'Europe/Athens',       label: '(UTC+02:00) Thessaloniki / 塞萨洛尼基',                   tad: 'greece/thessaloniki' },
  { value: 'Europe/Athens',       label: '(UTC+02:00) Patras / 帕特雷',                            tad: 'greece/patras' },
  { value: 'Europe/Helsinki',     label: '(UTC+02:00) Helsinki / 赫尔辛基',                       tad: 'finland/helsinki' },
  { value: 'Europe/Helsinki',     label: '(UTC+02:00) Tampere / 坦佩雷',                           tad: 'finland/tampere' },
  { value: 'Europe/Helsinki',     label: '(UTC+02:00) Oulu / 乌卢',                                tad: 'finland/oulu' },
  { value: 'Europe/Bucharest',    label: '(UTC+02:00) Bucharest / 布加勒斯特',                    tad: 'romania/bucharest' },
  { value: 'Europe/Sofia',        label: '(UTC+02:00) Sofia / 索非亚',                            tad: 'bulgaria/sofia' },
  { value: 'Europe/Riga',         label: '(UTC+02:00) Riga / 里加',                               tad: 'latvia/riga' },
  { value: 'Europe/Tallinn',      label: '(UTC+02:00) Tallinn / 塔林',                            tad: 'estonia/tallinn' },
  { value: 'Europe/Tallinn',      label: '(UTC+02:00) Tartu / 塔尔图',                             tad: 'estonia/tartu' },
  { value: 'Europe/Vilnius',      label: '(UTC+02:00) Vilnius / 维尔纽斯',                        tad: 'lithuania/vilnius' },
  { value: 'Europe/Vilnius',      label: '(UTC+02:00) Kaunas / 考纳斯',                            tad: 'lithuania/kaunas' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Kyiv / 基辅',                               tad: 'ukraine/kiev' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Odesa / 敖德萨',                              tad: 'ukraine/odesa' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Lviv / 利沃夫',                              tad: 'ukraine/lviv' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Kharkiv / 哈尔科夫',                          tad: 'ukraine/kharkiv' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Dnipro / 迪尼普罗',                          tad: 'ukraine/dnipro' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Istanbul / 伊斯坦布尔',                     tad: 'turkey/istanbul' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Ankara / 安卡拉',                            tad: 'turkey/ankara' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Izmir / 伊兹密尔',                            tad: 'turkey/izmir' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Antalya / 安塔利亚',                          tad: 'turkey/antalya' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Bursa / 布尔萨',                             tad: 'turkey/bursa' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Adana / 阿达纳',                              tad: 'turkey/adana' },
  { value: 'Europe/Moscow',       label: '(UTC+03:00) Moscow / 莫斯科',                           tad: 'russia/moscow' },
  { value: 'Europe/Moscow',       label: '(UTC+03:00) Saint Petersburg / 圣彼得堡',               tad: 'russia/saint-petersburg' },
  { value: 'Europe/Moscow',       label: '(UTC+03:00) Kazan / 喀山',                                tad: 'russia/kazan' },
  { value: 'Europe/Moscow',       label: '(UTC+03:00) Nizhny Novgorod / 下诺夫哥罗德',             tad: 'russia/nizhny-novgorod' },
  { value: 'Europe/Minsk',        label: '(UTC+03:00) Minsk / 明斯克',                            tad: 'belarus/minsk' },

  { value: 'Africa/Dakar',        label: '(UTC+00:00) Dakar / 达喀尔',                            tad: 'senegal/dakar' },
  { value: 'Africa/Accra',        label: '(UTC+00:00) Accra / 阿克拉',                            tad: 'ghana/accra' },
  { value: 'Africa/Lagos',        label: '(UTC+01:00) Lagos / 拉各斯',                            tad: 'nigeria/lagos' },
  { value: 'Africa/Algiers',      label: '(UTC+01:00) Algiers / 阿尔及尔',                          tad: 'algeria/algiers' },
  { value: 'Africa/Tunis',        label: '(UTC+01:00) Tunis / 突尼斯',                            tad: 'tunisia/tunis' },
  { value: 'Africa/Kinshasa',     label: '(UTC+01:00) Kinshasa / 金沙萨',                          tad: 'dr-congo/kinshasa' },
  { value: 'Africa/Cairo',        label: '(UTC+02:00) Cairo / 开罗',                              tad: 'egypt/cairo' },
  { value: 'Africa/Khartoum',     label: '(UTC+02:00) Khartoum / 喀土穆',                         tad: 'sudan/khartoum' },
  { value: 'Africa/Johannesburg', label: '(UTC+02:00) Johannesburg / 约翰内斯堡',                 tad: 'south-africa/johannesburg' },
  { value: 'Africa/Cape_Town',    label: '(UTC+02:00) Cape Town / 开普敦',                       tad: 'south-africa/cape-town' },
  { value: 'Africa/Addis_Ababa',  label: '(UTC+03:00) Addis Ababa / 亚的斯亚贝巴',               tad: 'ethiopia/addis-ababa' },
  { value: 'Africa/Nairobi',      label: '(UTC+03:00) Nairobi / 内罗毕',                          tad: 'kenya/nairobi' },

  { value: 'Asia/Jerusalem',      label: '(UTC+02:00) Jerusalem / 耶路撒冷',                      tad: 'israel/jerusalem' },
  { value: 'Asia/Jerusalem',      label: '(UTC+02:00) Tel Aviv / 特拉维夫',                        tad: 'israel/tel-aviv' },
  { value: 'Asia/Riyadh',         label: '(UTC+03:00) Riyadh / 利雅得',                           tad: 'saudi-arabia/riyadh' },
  { value: 'Asia/Riyadh',         label: '(UTC+03:00) Doha / 多哈',                                tad: 'qatar/doha' },
  { value: 'Asia/Riyadh',         label: '(UTC+03:00) Kuwait City / 科威特城',                      tad: 'kuwait/kuwait-city' },
  { value: 'Asia/Riyadh',         label: '(UTC+03:00) Baghdad / 巴格达',                            tad: 'iraq/baghdad' },
  { value: 'Asia/Tehran',         label: '(UTC+03:30) Tehran / 德黑兰',                           tad: 'iran/tehran' },
  { value: 'Europe/Samara',       label: '(UTC+04:00) Samara / 萨马拉',                            tad: 'russia/samara' },
  { value: 'Asia/Dubai',          label: '(UTC+04:00) Dubai / 迪拜',                              tad: 'united-arab-emirates/dubai' },
  { value: 'Asia/Muscat',         label: '(UTC+04:00) Muscat / 马斯喀特',                          tad: 'oman/muscat' },
  { value: 'Asia/Baku',           label: '(UTC+04:00) Baku / 巴库',                               tad: 'azerbaijan/baku' },

  { value: 'Asia/Karachi',        label: '(UTC+05:00) Karachi / 卡拉奇',                          tad: 'pakistan/karachi' },
  { value: 'Asia/Karachi',        label: '(UTC+05:00) Lahore / 拉合尔',                            tad: 'pakistan/lahore' },
  { value: 'Asia/Tashkent',       label: '(UTC+05:00) Tashkent / 塔什干',                         tad: 'uzbekistan/tashkent' },
  { value: 'Asia/Yekaterinburg',  label: '(UTC+05:00) Yekaterinburg / 叶卡捷琳堡',                tad: 'russia/yekaterinburg' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) New Delhi / 新德里',                        tad: 'india/new-delhi' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Mumbai / 孟买',                             tad: 'india/mumbai' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Bangalore / 班加罗尔',                        tad: 'india/bangalore' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Chennai / 清奈',                             tad: 'india/chennai' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Hyderabad / 海得拉巴',                       tad: 'india/hyderabad' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Ahmedabad / 艾哈迈达巴德',                   tad: 'india/ahmedabad' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Pune / 浦那',                                tad: 'india/pune' },
  { value: 'Asia/Colombo',        label: '(UTC+05:30) Colombo / 科伦坡',                          tad: 'sri-lanka/colombo' },
  { value: 'Asia/Kathmandu',      label: '(UTC+05:45) Kathmandu / 加德满都',                      tad: 'nepal/kathmandu' },
  { value: 'Asia/Dhaka',          label: '(UTC+06:00) Dhaka / 达卡',                              tad: 'bangladesh/dhaka' },
  { value: 'Asia/Dhaka',          label: '(UTC+06:00) Chittagong / 吉大港',                        tad: 'bangladesh/chittagong' },
  { value: 'Asia/Almaty',         label: '(UTC+06:00) Almaty / 阿拉木图',                         tad: 'kazakhstan/almaty' },
  { value: 'Asia/Omsk',           label: '(UTC+06:00) Omsk / 鄂木斯克',                            tad: 'russia/omsk' },
  { value: 'Asia/Novosibirsk',    label: '(UTC+06:00) Novosibirsk / 新西伯利亚',                 tad: 'russia/novosibirsk' },
  { value: 'Asia/Urumqi',         label: '(UTC+06:00) Urumqi / 乌鲁木齐',                         tad: 'china/urumqi' },
  { value: 'Asia/Yangon',         label: '(UTC+06:30) Yangon / 仰光',                             tad: 'myanmar/yangon' },

  { value: 'Asia/Bangkok',        label: '(UTC+07:00) Bangkok / 曼谷',                            tad: 'thailand/bangkok' },
  { value: 'Asia/Jakarta',        label: '(UTC+07:00) Jakarta / 雅加达',                          tad: 'indonesia/jakarta' },
  { value: 'Asia/Ho_Chi_Minh',    label: '(UTC+07:00) Ho Chi Minh City / 胡志明市',               tad: 'vietnam/ho-chi-minh-city' },
  { value: 'Asia/Krasnoyarsk',    label: '(UTC+07:00) Krasnoyarsk / 克拉斯诺亚尔斯克',             tad: 'russia/krasnoyarsk' },
  { value: 'Asia/Manila',         label: '(UTC+08:00) Manila / 马尼拉',                           tad: 'philippines/manila' },
  { value: 'Asia/Manila',         label: '(UTC+08:00) Cebu / 宿雾',                                 tad: 'philippines/cebu' },

  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Beijing / 北京',                            tad: 'china/beijing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shanghai / 上海',                           tad: 'china/shanghai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Guangzhou / 广州',                          tad: 'china/guangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shenzhen / 深圳',                           tad: 'china/shenzhen' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Chengdu / 成都',                            tad: 'china/chengdu' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Wuhan / 武汉',                              tad: 'china/wuhan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xi\'an / 西安',                             tad: 'china/xian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hangzhou / 杭州',                           tad: 'china/hangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanjing / 南京',                            tad: 'china/nanjing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Tianjin / 天津',                            tad: 'china/tianjin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shenyang / 沈阳',                           tad: 'china/shenyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Harbin / 哈尔滨',                           tad: 'china/harbin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Kunming / 昆明',                            tad: 'china/kunming' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhengzhou / 郑州',                          tad: 'china/zhengzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jinan / 济南',                              tad: 'china/jinan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Qingdao / 青岛',                            tad: 'china/qingdao' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Dalian / 大连',                              tad: 'china/dalian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Fuzhou / 福州',                              tad: 'china/fuzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xiamen / 厦门',                              tad: 'china/xiamen' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Suzhou / 苏州',                              tad: 'china/suzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Changsha / 长沙',                            tad: 'china/changsha' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Changchun / 长春',                          tad: 'china/changchun' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanning / 南宁',                            tad: 'china/nanning' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hefei / 合肥',                              tad: 'china/hefei' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Wuxi / 无锡',                               tad: 'china/wuxi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Ningbo / 宁波',                             tad: 'china/ningbo' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhuhai / 珠海',                              tad: 'china/zhuhai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Dongguan / 东莞',                            tad: 'china/dongguan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Foshan / 佛山',                              tad: 'china/foshan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanchang / 南昌',                            tad: 'china/nanchang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Changzhou / 常州',                           tad: 'china/changzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xuzhou / 徐州',                              tad: 'china/xuzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lanzhou / 兰州',                             tad: 'china/lanzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Taiyuan / 太原',                             tad: 'china/taiyuan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shijiazhuang / 石家庄',                      tad: 'china/shijiazhuang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Haikou / 海口',                              tad: 'china/haikou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Sanya / 三亚',                              tad: 'china/sanya' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lhasa / 拉萨',                              tad: 'china/lhasa' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yinchuan / 银川',                            tad: 'china/yinchuan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xining / 西宁',                              tad: 'china/xining' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Guiyang / 贵阳',                            tad: 'china/guiyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hohhot / 呼和浩特',                          tad: 'china/hohhot' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Weifang / 潍坊',                             tad: 'china/weifang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yantai / 烟台',                              tad: 'china/yantai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Wenzhou / 温州',                             tad: 'china/wenzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nantong / 南通',                             tad: 'china/nantong' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yangzhou / 扬州',                            tad: 'china/yangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Taizhou / 台州',                             tad: 'china/taizhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shaoxing / 绍兴',                            tad: 'china/shaoxing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jiaxing / 嘉兴',                             tad: 'china/jiaxing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Huzhou / 湖州',                             tad: 'china/huzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Quzhou / 衢州',                             tad: 'china/quzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhoushan / 舟山',                            tad: 'china/zhoushan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lianyungang / 连云港',                       tad: 'china/lianyungang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yancheng / 盐城',                            tad: 'china/yancheng' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhenjiang / 镇江',                           tad: 'china/zhenjiang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Huaian / 淮安',                             tad: 'china/huaian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Suqian / 宿迁',                             tad: 'china/suqian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jinhua / 金华',                             tad: 'china/jinhua' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lishui / 丽水',                             tad: 'china/lishui' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Quanzhou / 泉州',                            tad: 'china/quanzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhangzhou / 漳州',                           tad: 'china/zhangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Putian / 莆田',                             tad: 'china/putian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanping / 南平',                             tad: 'china/nanping' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Sanming / 三明',                             tad: 'china/sanming' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Ningde / 宁德',                             tad: 'china/ningde' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Longyan / 龙岩',                             tad: 'china/longyan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zibo / 淄博',                               tad: 'china/zibo' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jining / 济宁',                              tad: 'china/jining' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Taian / 泰安',                              tad: 'china/taian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Dezhou / 德州',                             tad: 'china/dezhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zaozhuang / 枣庄',                          tad: 'china/zaozhuang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Linyi / 临沂',                               tad: 'china/linyi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Dongying / 东营',                            tad: 'china/dongying' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Binzhou / 滨州',                             tad: 'china/binzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Rizhao / 日照',                              tad: 'china/rizhao' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Heze / 菏泽',                                tad: 'china/heze' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Weihai / 威海',                              tad: 'china/weihai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Luoyang / 洛阳',                             tad: 'china/luoyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Kaifeng / 开封',                             tad: 'china/kaifeng' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xinxiang / 新乡',                            tad: 'china/xinxiang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jiaozuo / 焦作',                             tad: 'china/jiaozuo' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanyang / 南阳',                             tad: 'china/nanyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shangqiu / 商丘',                            tad: 'china/shangqiu' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhumadian / 驻马店',                         tad: 'china/zhumadian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Puyang / 濮阳',                              tad: 'china/puyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Anyang / 安阳',                              tad: 'china/anyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhoukou / 周口',                             tad: 'china/zhoukou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xinyang / 信阳',                             tad: 'china/xinyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yichang / 宜昌',                             tad: 'china/yichang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xiangyang / 襄阳',                           tad: 'china/xiangyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jingzhou / 荆州',                            tad: 'china/jingzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Huangshi / 黄石',                            tad: 'china/huangshi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shiyan / 十堰',                              tad: 'china/shiyan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Ezhou / 鄂州',                               tad: 'china/ezhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xiaogan / 孝感',                             tad: 'china/xiaogan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Suizhou / 随州',                             tad: 'china/suizhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhuzhou / 株洲',                             tad: 'china/zhuzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xiangtan / 湘潭',                            tad: 'china/xiangtan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hengyang / 衡阳',                           tad: 'china/hengyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yueyang / 岳阳',                             tad: 'china/yueyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Changde / 常德',                             tad: 'china/changde' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhangjiajie / 张家界',                         tad: 'china/zhangjiajie' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Loudi / 娄底',                               tad: 'china/loudi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yiyang / 益阳',                              tad: 'china/yiyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Chenzhou / 郴州',                            tad: 'china/chenzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shaoyang / 邵阳',                             tad: 'china/shaoyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jingdezhen / 景德镇',                          tad: 'china/jingdezhen' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yingtan / 鹰潭',                             tad: 'china/yingtan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jiujiang / 九江',                            tad: 'china/jiujiang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Ganzhou / 赣州',                              tad: 'china/ganzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shangrao / 上饶',                            tad: 'china/shangrao' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yichun / 宜春',                              tad: 'china/yichun' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Pingxiang / 萍乡',                            tad: 'china/pingxiang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xinyu / 新余',                              tad: 'china/xinyu' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Liuzhou / 柳州',                             tad: 'china/liuzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Guilin / 桂林',                              tad: 'china/guilin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Wuzhou / 梧州',                              tad: 'china/wuzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Beihai / 北海',                              tad: 'china/beihai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Qinzhou / 钦州',                            tad: 'china/qinzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Fangchenggang / 防城港',                      tad: 'china/fangchenggang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yulin / 玉林',                              tad: 'china/yulin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hezhou / 贺州',                              tad: 'china/hezhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Baise / 百色',                               tad: 'china/baise' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zunyi / 遵义',                               tad: 'china/zunyi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Anshun / 安顺',                              tad: 'china/anshun' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Tongren / 铜仁',                             tad: 'china/tongren' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Bijie / 毕节',                               tad: 'china/bijie' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Liupanshui / 六盘水',                         tad: 'china/liupanshui' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Yuxi / 玉溪',                                tad: 'china/yuxi' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Qujing / 曲靖',                             tad: 'china/qujing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Chuxiong / 楚雄',                            tad: 'china/chuxiong' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lijiang / 丽江',                             tad: 'china/lijiang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Baoshan / 保山',                             tad: 'china/baoshan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhaotong / 昭通',                            tad: 'china/zhaotong' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Puer / 普洱',                               tad: 'china/puer' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Dali / 大理',                                tad: 'china/dali' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Lincang / 临沧',                             tad: 'china/lincang' },
  { value: 'Asia/Chongqing',      label: '(UTC+08:00) Chongqing / 重庆',                          tad: 'china/chongqing' },
  { value: 'Asia/Hong_Kong',      label: '(UTC+08:00) Hong Kong / 香港',                          tad: 'china/hong-kong' },
  { value: 'Asia/Hong_Kong',      label: '(UTC+08:00) Macau / 澳门',                                tad: 'china/macau' },
  { value: 'Asia/Taipei',         label: '(UTC+08:00) Taipei / 台北',                             tad: 'taiwan/taipei' },
  { value: 'Asia/Taipei',         label: '(UTC+08:00) Kaohsiung / 高雄',                            tad: 'taiwan/kaohsiung' },
  { value: 'Asia/Kuala_Lumpur',   label: '(UTC+08:00) Kuala Lumpur / 吉隆坡',                     tad: 'malaysia/kuala-lumpur' },
  { value: 'Asia/Singapore',      label: '(UTC+08:00) Singapore / 新加坡',                        tad: 'singapore/singapore' },
  { value: 'Australia/Perth',     label: '(UTC+08:00) Perth / 珀斯',                              tad: 'australia/perth' },

  { value: 'Asia/Seoul',          label: '(UTC+09:00) Seoul / 首尔',                              tad: 'south-korea/seoul' },
  { value: 'Asia/Seoul',          label: '(UTC+09:00) Busan / 釜山',                               tad: 'south-korea/busan' },
  { value: 'Asia/Seoul',          label: '(UTC+09:00) Incheon / 仁川',                             tad: 'south-korea/incheon' },
  { value: 'Asia/Tokyo',          label: '(UTC+09:00) Tokyo / 东京',                              tad: 'japan/tokyo' },
  { value: 'Asia/Tokyo',          label: '(UTC+09:00) Osaka / 大阪',                               tad: 'japan/osaka' },
  { value: 'Asia/Tokyo',          label: '(UTC+09:00) Kyoto / 京都',                               tad: 'japan/kyoto' },
  { value: 'Asia/Yakutsk',        label: '(UTC+09:00) Yakutsk / 雅库茨克',                          tad: 'russia/yakutsk' },
  { value: 'Australia/Adelaide',  label: '(UTC+09:30) Adelaide / 阿德莱德',                       tad: 'australia/adelaide' },
  { value: 'Australia/Darwin',    label: '(UTC+09:30) Darwin / 达尔文',                           tad: 'australia/darwin' },
  { value: 'Australia/Sydney',    label: '(UTC+10:00) Sydney / 悉尼',                             tad: 'australia/sydney' },
  { value: 'Australia/Canberra',  label: '(UTC+10:00) Canberra / 堪培拉',                         tad: 'australia/canberra' },
  { value: 'Australia/Hobart',    label: '(UTC+10:00) Hobart / 霍巴特',                           tad: 'australia/hobart' },
  { value: 'Australia/Melbourne', label: '(UTC+10:00) Melbourne / 墨尔本',                        tad: 'australia/melbourne' },
  { value: 'Australia/Brisbane',  label: '(UTC+10:00) Brisbane / 布里斯班',                       tad: 'australia/brisbane' },
  { value: 'Pacific/Guam',        label: '(UTC+10:00) Guam / 关岛',                               tad: 'guam/hagatna' },
  { value: 'Pacific/Port_Moresby', label: '(UTC+10:00) Port Moresby / 莫尔兹比港',                tad: 'papua-new-guinea/port-moresby' },
  { value: 'Asia/Vladivostok',    label: '(UTC+10:00) Vladivostok / 符拉迪沃斯托克',              tad: 'russia/vladivostok' },
  { value: 'Asia/Khabarovsk',     label: '(UTC+10:00) Khabarovsk / 哈巴罗夫斯克',                  tad: 'russia/khabarovsk' },
  { value: 'Pacific/Noumea',      label: '(UTC+11:00) Nouméa / 努美阿',                           tad: 'new-caledonia/noumea' },
  { value: 'Pacific/Auckland',    label: '(UTC+12:00) Auckland / 奥克兰',                         tad: 'new-zealand/auckland' },
  { value: 'Pacific/Auckland',    label: '(UTC+12:00) Wellington / 惠灵顿',                       tad: 'new-zealand/wellington' },
  { value: 'Pacific/Auckland',    label: '(UTC+12:00) Christchurch / 基督城',                     tad: 'new-zealand/christchurch' },
  { value: 'Pacific/Fiji',        label: '(UTC+12:00) Suva / 斐济-苏瓦',                          tad: 'fiji/suva' },
  { value: 'Pacific/Tongatapu',   label: '(UTC+13:00) Nukuʻalofa / 努库阿洛法',                   tad: 'tonga/nukualofa' },
];
