// All IANA timezones grouped for the select dropdown
const TIMEZONE_LIST = [
  { value: 'Pacific/Midway',       label: '(UTC-11:00) 中途岛' },
  { value: 'Pacific/Honolulu',     label: '(UTC-10:00) 夏威夷' },
  { value: 'America/Anchorage',    label: '(UTC-09:00) 阿拉斯加' },
  { value: 'America/Los_Angeles',  label: '(UTC-08:00) 洛杉矶 / 太平洋时间' },
  { value: 'America/Denver',       label: '(UTC-07:00) 丹佛 / 山地时间' },
  { value: 'America/Phoenix',      label: '(UTC-07:00) 菲尼克斯（无夏令时）' },
  { value: 'America/Chicago',      label: '(UTC-06:00) 芝加哥 / 中部时间' },
  { value: 'America/Mexico_City',  label: '(UTC-06:00) 墨西哥城' },
  { value: 'America/New_York',     label: '(UTC-05:00) 纽约 / 东部时间' },
  { value: 'America/Toronto',      label: '(UTC-05:00) 多伦多' },
  { value: 'America/Bogota',       label: '(UTC-05:00) 波哥大' },
  { value: 'America/Lima',         label: '(UTC-05:00) 利马' },
  { value: 'America/Caracas',      label: '(UTC-04:30) 加拉加斯' },
  { value: 'America/Halifax',      label: '(UTC-04:00) 哈利法克斯' },
  { value: 'America/Santiago',     label: '(UTC-04:00) 圣地亚哥' },
  { value: 'America/Sao_Paulo',    label: '(UTC-03:00) 圣保罗' },
  { value: 'America/Argentina/Buenos_Aires', label: '(UTC-03:00) 布宜诺斯艾利斯' },
  { value: 'Atlantic/South_Georgia', label: '(UTC-02:00) 南乔治亚岛' },
  { value: 'Atlantic/Azores',      label: '(UTC-01:00) 亚速尔群岛' },
  { value: 'Atlantic/Cape_Verde',  label: '(UTC-01:00) 佛得角' },
  { value: 'Europe/London',        label: '(UTC+00:00) 伦敦 / 格林威治' },
  { value: 'Europe/Lisbon',        label: '(UTC+00:00) 里斯本' },
  { value: 'Africa/Casablanca',    label: '(UTC+00:00) 卡萨布兰卡' },
  { value: 'Europe/Paris',         label: '(UTC+01:00) 巴黎 / 柏林 / 中欧' },
  { value: 'Europe/Berlin',        label: '(UTC+01:00) 柏林' },
  { value: 'Europe/Rome',          label: '(UTC+01:00) 罗马' },
  { value: 'Europe/Madrid',        label: '(UTC+01:00) 马德里' },
  { value: 'Africa/Lagos',         label: '(UTC+01:00) 拉各斯' },
  { value: 'Europe/Athens',        label: '(UTC+02:00) 雅典 / 东欧' },
  { value: 'Europe/Helsinki',      label: '(UTC+02:00) 赫尔辛基' },
  { value: 'Europe/Istanbul',      label: '(UTC+03:00) 伊斯坦布尔' },
  { value: 'Africa/Cairo',         label: '(UTC+02:00) 开罗' },
  { value: 'Africa/Johannesburg',  label: '(UTC+02:00) 约翰内斯堡' },
  { value: 'Asia/Jerusalem',       label: '(UTC+02:00) 耶路撒冷' },
  { value: 'Europe/Moscow',        label: '(UTC+03:00) 莫斯科' },
  { value: 'Asia/Riyadh',          label: '(UTC+03:00) 利雅得' },
  { value: 'Africa/Nairobi',       label: '(UTC+03:00) 内罗毕' },
  { value: 'Asia/Tehran',          label: '(UTC+03:30) 德黑兰' },
  { value: 'Asia/Dubai',           label: '(UTC+04:00) 迪拜' },
  { value: 'Asia/Baku',            label: '(UTC+04:00) 巴库' },
  { value: 'Asia/Kabul',           label: '(UTC+04:30) 喀布尔' },
  { value: 'Asia/Karachi',         label: '(UTC+05:00) 卡拉奇' },
  { value: 'Asia/Tashkent',        label: '(UTC+05:00) 塔什干' },
  { value: 'Asia/Kolkata',         label: '(UTC+05:30) 印度 / 孟买 / 新德里' },
  { value: 'Asia/Colombo',         label: '(UTC+05:30) 科伦坡' },
  { value: 'Asia/Kathmandu',       label: '(UTC+05:45) 加德满都' },
  { value: 'Asia/Dhaka',           label: '(UTC+06:00) 达卡' },
  { value: 'Asia/Almaty',          label: '(UTC+06:00) 阿拉木图' },
  { value: 'Asia/Rangoon',         label: '(UTC+06:30) 仰光' },
  { value: 'Asia/Bangkok',         label: '(UTC+07:00) 曼谷 / 雅加达' },
  { value: 'Asia/Ho_Chi_Minh',     label: '(UTC+07:00) 胡志明市' },
  { value: 'Asia/Jakarta',         label: '(UTC+07:00) 雅加达' },
  { value: 'Asia/Shanghai',        label: '(UTC+08:00) 北京 / 上海 / 重庆' },
  { value: 'Asia/Hong_Kong',       label: '(UTC+08:00) 香港' },
  { value: 'Asia/Taipei',          label: '(UTC+08:00) 台北' },
  { value: 'Asia/Kuala_Lumpur',    label: '(UTC+08:00) 吉隆坡' },
  { value: 'Asia/Singapore',       label: '(UTC+08:00) 新加坡' },
  { value: 'Australia/Perth',      label: '(UTC+08:00) 珀斯' },
  { value: 'Asia/Seoul',           label: '(UTC+09:00) 首尔' },
  { value: 'Asia/Tokyo',           label: '(UTC+09:00) 东京' },
  { value: 'Australia/Adelaide',   label: '(UTC+09:30) 阿德莱德' },
  { value: 'Australia/Darwin',     label: '(UTC+09:30) 达尔文' },
  { value: 'Australia/Sydney',     label: '(UTC+10:00) 悉尼 / 墨尔本' },
  { value: 'Australia/Brisbane',   label: '(UTC+10:00) 布里斯班' },
  { value: 'Pacific/Guam',         label: '(UTC+10:00) 关岛' },
  { value: 'Asia/Vladivostok',     label: '(UTC+10:00) 符拉迪沃斯托克' },
  { value: 'Pacific/Noumea',       label: '(UTC+11:00) 努美阿' },
  { value: 'Pacific/Auckland',     label: '(UTC+12:00) 奥克兰 / 惠灵顿' },
  { value: 'Pacific/Fiji',         label: '(UTC+12:00) 斐济' },
  { value: 'Pacific/Tongatapu',    label: '(UTC+13:00) 努库阿洛法' },
];

// IANA timezone → timeanddate.com /worldclock/{path} direct URL mapping
const TZ_TIMEANDDATE = {
  'Pacific/Midway':                      'samoa/apia',
  'Pacific/Honolulu':                    'usa/honolulu',
  'America/Anchorage':                   'usa/anchorage',
  'America/Los_Angeles':                 'usa/los-angeles',
  'America/Denver':                      'usa/denver',
  'America/Phoenix':                     'usa/phoenix',
  'America/Chicago':                     'usa/chicago',
  'America/Mexico_City':                 'mexico/mexico-city',
  'America/New_York':                    'usa/new-york',
  'America/Toronto':                     'canada/toronto',
  'America/Bogota':                      'colombia/bogota',
  'America/Lima':                        'peru/lima',
  'America/Caracas':                     'venezuela/caracas',
  'America/Halifax':                     'canada/halifax',
  'America/Santiago':                    'chile/santiago',
  'America/Sao_Paulo':                   'brazil/sao-paulo',
  'America/Argentina/Buenos_Aires':      'argentina/buenos-aires',
  'Atlantic/South_Georgia':             'falkland/stanley',
  'Atlantic/Azores':                     'portugal/azores',
  'Atlantic/Cape_Verde':                 'cape-verde/praia',
  'Europe/London':                       'uk/london',
  'Europe/Lisbon':                       'portugal/lisbon',
  'Africa/Casablanca':                   'morocco/casablanca',
  'Europe/Paris':                        'france/paris',
  'Europe/Berlin':                       'germany/berlin',
  'Europe/Rome':                         'italy/rome',
  'Europe/Madrid':                       'spain/madrid',
  'Africa/Lagos':                        'nigeria/lagos',
  'Europe/Athens':                       'greece/athens',
  'Europe/Helsinki':                     'finland/helsinki',
  'Europe/Istanbul':                     'turkey/istanbul',
  'Africa/Cairo':                        'egypt/cairo',
  'Africa/Johannesburg':                 'south-africa/johannesburg',
  'Asia/Jerusalem':                      'israel/jerusalem',
  'Europe/Moscow':                       'russia/moscow',
  'Asia/Riyadh':                         'saudi-arabia/riyadh',
  'Africa/Nairobi':                      'kenya/nairobi',
  'Asia/Tehran':                         'iran/tehran',
  'Asia/Dubai':                          'united-arab-emirates/dubai',
  'Asia/Baku':                           'azerbaijan/baku',
  'Asia/Kabul':                          'afghanistan/kabul',
  'Asia/Karachi':                        'pakistan/karachi',
  'Asia/Tashkent':                       'uzbekistan/tashkent',
  'Asia/Kolkata':                        'india/new-delhi',
  'Asia/Colombo':                        'sri-lanka/colombo',
  'Asia/Kathmandu':                      'nepal/kathmandu',
  'Asia/Dhaka':                          'bangladesh/dhaka',
  'Asia/Almaty':                         'kazakhstan/almaty',
  'Asia/Rangoon':                        'myanmar/rangoon',
  'Asia/Bangkok':                        'thailand/bangkok',
  'Asia/Ho_Chi_Minh':                    'vietnam/ho-chi-minh-city',
  'Asia/Jakarta':                        'indonesia/jakarta',
  'Asia/Shanghai':                       'china/shanghai',
  'Asia/Hong_Kong':                      'china/hong-kong',
  'Asia/Taipei':                         'taiwan/taipei',
  'Asia/Kuala_Lumpur':                   'malaysia/kuala-lumpur',
  'Asia/Singapore':                      'singapore/singapore',
  'Australia/Perth':                     'australia/perth',
  'Asia/Seoul':                          'south-korea/seoul',
  'Asia/Tokyo':                          'japan/tokyo',
  'Australia/Adelaide':                  'australia/adelaide',
  'Australia/Darwin':                    'australia/darwin',
  'Australia/Sydney':                    'australia/sydney',
  'Australia/Brisbane':                  'australia/brisbane',
  'Pacific/Guam':                        'guam/hagatna',
  'Asia/Vladivostok':                    'russia/vladivostok',
  'Pacific/Noumea':                      'new-caledonia/noumea',
  'Pacific/Auckland':                    'new-zealand/auckland',
  'Pacific/Fiji':                        'fiji/suva',
  'Pacific/Tongatapu':                   'tonga/nukualofa',
};
