// All IANA timezones grouped for the select dropdown.
// Each entry has: value (IANA zone), label (bilingual display), tad (timeanddate.com worldclock path).
const TIMEZONE_LIST = [
  { value: 'Pacific/Midway',      label: '(UTC-11:00) Midway / 中途岛',                          tad: 'pacific/apia' },
  { value: 'Pacific/Honolulu',    label: '(UTC-10:00) Honolulu / 夏威夷-檀香山',                  tad: 'usa/honolulu' },
  { value: 'America/Anchorage',   label: '(UTC-09:00) Anchorage / 安克雷奇',                      tad: 'usa/anchorage' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Los Angeles / 洛杉矶',                      tad: 'usa/los-angeles' },
  { value: 'America/Vancouver',   label: '(UTC-08:00) Vancouver / 温哥华',                        tad: 'canada/vancouver' },
  { value: 'America/Denver',      label: '(UTC-07:00) Denver / 丹佛',                             tad: 'usa/denver' },
  { value: 'America/Phoenix',     label: '(UTC-07:00) Phoenix / 菲尼克斯',                        tad: 'usa/phoenix' },
  { value: 'America/Chicago',     label: '(UTC-06:00) Chicago / 芝加哥',                          tad: 'usa/chicago' },
  { value: 'America/Mexico_City', label: '(UTC-06:00) Mexico City / 墨西哥城',                    tad: 'mexico/mexico-city' },
  { value: 'America/Toronto',     label: '(UTC-05:00) Toronto / 多伦多',                          tad: 'canada/toronto' },
  { value: 'America/New_York',    label: '(UTC-05:00) New York / 纽约',                           tad: 'usa/new-york' },
  { value: 'America/Bogota',      label: '(UTC-05:00) Bogotá / 波哥大',                           tad: 'colombia/bogota' },
  { value: 'America/Lima',        label: '(UTC-05:00) Lima / 利马',                               tad: 'peru/lima' },
  { value: 'America/Detroit',     label: '(UTC-05:00) Detroit / 底特律',                          tad: 'usa/detroit' },
  { value: 'America/Indiana/Indianapolis', label: '(UTC-05:00) Indianapolis / 印第安纳波利斯',    tad: 'usa/indianapolis' },
  { value: 'America/Halifax',     label: '(UTC-04:00) Halifax / 哈利法克斯',                      tad: 'canada/halifax' },
  { value: 'America/Caracas',     label: '(UTC-04:30) Caracas / 加拉加斯',                        tad: 'venezuela/caracas' },
  { value: 'America/Santiago',    label: '(UTC-04:00) Santiago / 圣地亚哥',                       tad: 'chile/santiago' },
  { value: 'America/Asuncion',    label: '(UTC-04:00) Asunción / 亚松森',                         tad: 'paraguay/asuncion' },
  { value: 'America/Sao_Paulo',   label: '(UTC-03:00) São Paulo / 圣保罗',                        tad: 'brazil/sao-paulo' },
  { value: 'America/Argentina/Buenos_Aires', label: '(UTC-03:00) Buenos Aires / 布宜诺斯艾利斯',  tad: 'argentina/buenos-aires' },
  { value: 'America/Montevideo',  label: '(UTC-03:00) Montevideo / 蒙得维的亚',                   tad: 'uruguay/montevideo' },

  { value: 'Europe/London',       label: '(UTC+00:00) London / 伦敦',                             tad: 'uk/london' },
  { value: 'Europe/Dublin',       label: '(UTC+00:00) Dublin / 都柏林',                           tad: 'ireland/dublin' },
  { value: 'Europe/Lisbon',       label: '(UTC+00:00) Lisbon / 里斯本',                           tad: 'portugal/lisbon' },
  { value: 'Europe/Paris',        label: '(UTC+01:00) Paris / 巴黎',                              tad: 'france/paris' },
  { value: 'Europe/Berlin',       label: '(UTC+01:00) Berlin / 柏林',                             tad: 'germany/berlin' },
  { value: 'Europe/Amsterdam',    label: '(UTC+01:00) Amsterdam / 阿姆斯特丹',                    tad: 'netherlands/amsterdam' },
  { value: 'Europe/Zurich',       label: '(UTC+01:00) Zurich / 苏黎世',                           tad: 'switzerland/zurich' },
  { value: 'Europe/Madrid',       label: '(UTC+01:00) Madrid / 马德里',                           tad: 'spain/madrid' },
  { value: 'Europe/Rome',         label: '(UTC+01:00) Rome / 罗马',                               tad: 'italy/rome' },
  { value: 'Europe/Stockholm',    label: '(UTC+01:00) Stockholm / 斯德哥尔摩',                    tad: 'sweden/stockholm' },
  { value: 'Europe/Oslo',         label: '(UTC+01:00) Oslo / 奥斯陆',                             tad: 'norway/oslo' },
  { value: 'Europe/Copenhagen',   label: '(UTC+01:00) Copenhagen / 哥本哈根',                     tad: 'denmark/copenhagen' },
  { value: 'Europe/Prague',       label: '(UTC+01:00) Prague / 布拉格',                           tad: 'czech-republic/prague' },
  { value: 'Europe/Brussels',     label: '(UTC+01:00) Brussels / 布鲁塞尔',                       tad: 'belgium/brussels' },
  { value: 'Europe/Vienna',       label: '(UTC+01:00) Vienna / 维也纳',                           tad: 'austria/vienna' },
  { value: 'Europe/Budapest',     label: '(UTC+01:00) Budapest / 布达佩斯',                       tad: 'hungary/budapest' },
  { value: 'Europe/Warsaw',       label: '(UTC+01:00) Warsaw / 华沙',                             tad: 'poland/warsaw' },
  { value: 'Europe/Zagreb',       label: '(UTC+01:00) Zagreb / 萨格勒布',                         tad: 'croatia/zagreb' },
  { value: 'Europe/Belgrade',     label: '(UTC+01:00) Belgrade / 贝尔格莱德',                     tad: 'serbia/belgrade' },
  { value: 'Europe/Bratislava',   label: '(UTC+01:00) Bratislava / 布拉迪斯拉发',                 tad: 'slovakia/bratislava' },
  { value: 'Europe/Ljubljana',    label: '(UTC+01:00) Ljubljana / 卢布尔雅那',                    tad: 'slovenia/ljubljana' },
  { value: 'Europe/Athens',       label: '(UTC+02:00) Athens / 雅典',                             tad: 'greece/athens' },
  { value: 'Europe/Helsinki',     label: '(UTC+02:00) Helsinki / 赫尔辛基',                       tad: 'finland/helsinki' },
  { value: 'Europe/Bucharest',    label: '(UTC+02:00) Bucharest / 布加勒斯特',                    tad: 'romania/bucharest' },
  { value: 'Europe/Sofia',        label: '(UTC+02:00) Sofia / 索非亚',                            tad: 'bulgaria/sofia' },
  { value: 'Europe/Riga',         label: '(UTC+02:00) Riga / 里加',                               tad: 'latvia/riga' },
  { value: 'Europe/Tallinn',      label: '(UTC+02:00) Tallinn / 塔林',                            tad: 'estonia/tallinn' },
  { value: 'Europe/Vilnius',      label: '(UTC+02:00) Vilnius / 维尔纽斯',                        tad: 'lithuania/vilnius' },
  { value: 'Europe/Kiev',         label: '(UTC+02:00) Kyiv / 基辅',                               tad: 'ukraine/kiev' },
  { value: 'Europe/Istanbul',     label: '(UTC+03:00) Istanbul / 伊斯坦布尔',                     tad: 'turkey/istanbul' },
  { value: 'Europe/Moscow',       label: '(UTC+03:00) Moscow / 莫斯科',                           tad: 'russia/moscow' },
  { value: 'Europe/Minsk',        label: '(UTC+03:00) Minsk / 明斯克',                            tad: 'belarus/minsk' },

  { value: 'Africa/Cairo',        label: '(UTC+02:00) Cairo / 开罗',                              tad: 'egypt/cairo' },
  { value: 'Africa/Lagos',        label: '(UTC+01:00) Lagos / 拉各斯',                            tad: 'nigeria/lagos' },
  { value: 'Africa/Johannesburg', label: '(UTC+02:00) Johannesburg / 约翰内斯堡',                 tad: 'south-africa/johannesburg' },
  { value: 'Africa/Nairobi',      label: '(UTC+03:00) Nairobi / 内罗毕',                          tad: 'kenya/nairobi' },

  { value: 'Asia/Jerusalem',      label: '(UTC+02:00) Jerusalem / 耶路撒冷',                      tad: 'israel/jerusalem' },
  { value: 'Asia/Riyadh',         label: '(UTC+03:00) Riyadh / 利雅得',                           tad: 'saudi-arabia/riyadh' },
  { value: 'Asia/Tehran',         label: '(UTC+03:30) Tehran / 德黑兰',                           tad: 'iran/tehran' },
  { value: 'Asia/Dubai',          label: '(UTC+04:00) Dubai / 迪拜',                              tad: 'united-arab-emirates/dubai' },
  { value: 'Asia/Baku',           label: '(UTC+04:00) Baku / 巴库',                               tad: 'azerbaijan/baku' },

  { value: 'Asia/Karachi',        label: '(UTC+05:00) Karachi / 卡拉奇',                          tad: 'pakistan/karachi' },
  { value: 'Asia/Tashkent',       label: '(UTC+05:00) Tashkent / 塔什干',                         tad: 'uzbekistan/tashkent' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) New Delhi / 新德里',                        tad: 'india/new-delhi' },
  { value: 'Asia/Kolkata',        label: '(UTC+05:30) Mumbai / 孟买',                             tad: 'india/mumbai' },
  { value: 'Asia/Colombo',        label: '(UTC+05:30) Colombo / 科伦坡',                          tad: 'sri-lanka/colombo' },
  { value: 'Asia/Kathmandu',      label: '(UTC+05:45) Kathmandu / 加德满都',                      tad: 'nepal/kathmandu' },
  { value: 'Asia/Dhaka',          label: '(UTC+06:00) Dhaka / 达卡',                              tad: 'bangladesh/dhaka' },
  { value: 'Asia/Almaty',         label: '(UTC+06:00) Almaty / 阿拉木图',                         tad: 'kazakhstan/almaty' },
  { value: 'Asia/Urumqi',         label: '(UTC+06:00) Urumqi / 乌鲁木齐',                         tad: 'china/urumqi' },
  { value: 'Asia/Yangon',         label: '(UTC+06:30) Yangon / 仰光',                             tad: 'myanmar/yangon' },

  { value: 'Asia/Bangkok',        label: '(UTC+07:00) Bangkok / 曼谷',                            tad: 'thailand/bangkok' },
  { value: 'Asia/Jakarta',        label: '(UTC+07:00) Jakarta / 雅加达',                          tad: 'indonesia/jakarta' },
  { value: 'Asia/Ho_Chi_Minh',    label: '(UTC+07:00) Ho Chi Minh City / 胡志明市',               tad: 'vietnam/ho-chi-minh-city' },
  { value: 'Asia/Manila',         label: '(UTC+08:00) Manila / 马尼拉',                           tad: 'philippines/manila' },

  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Beijing / 北京',                            tad: 'china/beijing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shanghai / 上海',                           tad: 'china/shanghai' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Guangzhou / 广州',                          tad: 'china/guangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shenzhen / 深圳',                           tad: 'china/shenzhen' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Chengdu / 成都',                            tad: 'china/chengdu' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Wuhan / 武汉',                              tad: 'china/wuhan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Xi\'an / 西安',                             tad: 'china/xian' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Hangzhou / 杭州',                           tad: 'china/hangzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Nanjing / 南京',                            tad: 'china/nanjing' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Tianjin / 天津',                            tad: 'china/tianjin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Shenyang / 沈阳',                           tad: 'china/shenyang' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Harbin / 哈尔滨',                           tad: 'china/harbin' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Kunming / 昆明',                            tad: 'china/kunming' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Zhengzhou / 郑州',                          tad: 'china/zhengzhou' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Jinan / 济南',                              tad: 'china/jinan' },
  { value: 'Asia/Shanghai',       label: '(UTC+08:00) Qingdao / 青岛',                            tad: 'china/qingdao' },
  { value: 'Asia/Chongqing',      label: '(UTC+08:00) Chongqing / 重庆',                          tad: 'china/chongqing' },
  { value: 'Asia/Hong_Kong',      label: '(UTC+08:00) Hong Kong / 香港',                          tad: 'china/hong-kong' },
  { value: 'Asia/Taipei',         label: '(UTC+08:00) Taipei / 台北',                             tad: 'taiwan/taipei' },
  { value: 'Asia/Kuala_Lumpur',   label: '(UTC+08:00) Kuala Lumpur / 吉隆坡',                     tad: 'malaysia/kuala-lumpur' },
  { value: 'Asia/Singapore',      label: '(UTC+08:00) Singapore / 新加坡',                        tad: 'singapore/singapore' },
  { value: 'Australia/Perth',     label: '(UTC+08:00) Perth / 珀斯',                              tad: 'australia/perth' },

  { value: 'Asia/Seoul',          label: '(UTC+09:00) Seoul / 首尔',                              tad: 'south-korea/seoul' },
  { value: 'Asia/Tokyo',          label: '(UTC+09:00) Tokyo / 东京',                              tad: 'japan/tokyo' },
  { value: 'Australia/Adelaide',  label: '(UTC+09:30) Adelaide / 阿德莱德',                       tad: 'australia/adelaide' },
  { value: 'Australia/Darwin',    label: '(UTC+09:30) Darwin / 达尔文',                           tad: 'australia/darwin' },
  { value: 'Australia/Sydney',    label: '(UTC+10:00) Sydney / 悉尼',                             tad: 'australia/sydney' },
  { value: 'Australia/Melbourne', label: '(UTC+10:00) Melbourne / 墨尔本',                        tad: 'australia/melbourne' },
  { value: 'Australia/Brisbane',  label: '(UTC+10:00) Brisbane / 布里斯班',                       tad: 'australia/brisbane' },
  { value: 'Pacific/Guam',        label: '(UTC+10:00) Guam / 关岛',                               tad: 'guam/hagatna' },
  { value: 'Pacific/Port_Moresby', label: '(UTC+10:00) Port Moresby / 莫尔兹比港',                tad: 'papua-new-guinea/port-moresby' },
  { value: 'Asia/Vladivostok',    label: '(UTC+10:00) Vladivostok / 符拉迪沃斯托克',              tad: 'russia/vladivostok' },
  { value: 'Pacific/Noumea',      label: '(UTC+11:00) Nouméa / 努美阿',                           tad: 'new-caledonia/noumea' },
  { value: 'Pacific/Auckland',    label: '(UTC+12:00) Auckland / 奥克兰',                         tad: 'new-zealand/auckland' },
  { value: 'Pacific/Fiji',        label: '(UTC+12:00) Suva / 斐济-苏瓦',                          tad: 'fiji/suva' },
  { value: 'Pacific/Tongatapu',   label: '(UTC+13:00) Nukuʻalofa / 努库阿洛法',                   tad: 'tonga/nukualofa' },
];
